import type { Metadata } from 'next';
import { Inter, Roboto_Condensed } from 'next/font/google';
import '../styles/globals.css';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';

const primaryFont = Inter({ subsets: ['latin'], weight: ['300', '700'], variable: '--font-primary' });
const secondaryFont = Roboto_Condensed({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-secondary' });

export const metadata: Metadata = {
  title: 'Cashapps',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${primaryFont.variable} ${secondaryFont.variable}`}>
      <body className="primaryFont.className">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
